github_username: DivineSMG
display_name: "Divine Azodo"
bio_code: 'cout << "this user likes to commit!!" << endl;'
linkedin_url: "https://www.linkedin.com/in/divineazodo"
external_gif_url: "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExZzJ1amU0NmpyOWIyZzBmd3EwaWU0NW91a21lMmdlMjVlbjJhNHBseSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/EZr27ZbJwmjE9PGyLN/giphy.gif"
gif_path: "assets/animated-coder.gif"
branch_name: "Main"
show_github_stats: true
show_top_languages: true
show_recent_commits: true
show_visitor_badge: true
show_last_updated: true
